### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Josh865** [Josh865/eeds-react-native#7]
- [ ] Use server error message for invalid sign in code
- [ ] Make splash screen background color blue so it works well in both with both light and dark themes
- [ ] Use web browser instead of WebView if device is Android 5 or lower
- [ ] Refresh home screen on focus
- [ ] Check temp account status on screen focus
- [ ] WebView should use mobile site's dark theme
